---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Services:
    - Traefik:
        icon: traefik.png #icons found here https://github.com/walkxcode/dashboard-icons
        href: https://traefik.ruzevich.com
        description:
    - Portainer:
        icon: portainer.png
        href: https://portainer.ruzevich.com
        description:
    - Tautulli:
        icon: tautulli.png
        href: https://tautulli.ruzevich.com
        description:
    - Dozzle:
        icon: dozzle.png
        href: https://dozzle.ruzevich.com/
        description:
    - Uptime-Kuma:
        icon: uptime-kuma.png
        href: https://kuma.ruzevich.com/
        description:

- Network Infra:
    - Pi-Hole:
        icon: pi-hole.png
        href: http://10.11.12.12/admin
        widget:
          type: pihole
          url: http://10.11.12.12/admin/api.php?status&auth=<TOKEN>
          key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}" # optional

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description:
