---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Peachy Homepage

background: https://images.pexels.com/photos/1366919/pexels-photo-1366919.jpeg

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
