---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Peachy Homepage

background: https://unsplash.com/photos/an-underwater-view-of-a-colorful-coral-reef-HYHYGLs-Rp8

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
