---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Peachy Homepage

background: https://images.pexels.com/photos/36717/amazing-animal-beautiful-beautifull.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
