---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Peachy Homepage

background:
  image: https://images.pexels.com/photos/1624496/pexels-photo-1624496.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
